name: Fetch Weather Data from Private Repo

on:
  # 在推送到主分支时触发
  push:
    branches: ["main"]
  
  # 允许手动触发
  workflow_dispatch:
  
  # 定时任务：每6小时运行一次
  schedule:
    - cron: '0 */6 * * *'

jobs:
  fetch-weather-data:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出当前公共仓库
      - name: Checkout current repository
        uses: actions/checkout@v4
        
      # 2. 从私有仓库拉取 weather_data.json
      - name: Fetch weather data from private repo
        uses: actions/checkout@v4
        with:
          repository: su-12321/weather-
          token: ${{ secrets.ACCESS_TOKEN }}
          path: temp-private-repo
          sparse-checkout: |
            weather_data.json
          sparse-checkout-cone-mode: false
        
      # 3. 创建data目录（如果不存在）并复制文件
      - name: Copy weather data to data directory
        run: |
          mkdir -p data
          cp temp-private-repo/weather_data.json data/
          echo "文件已复制到data目录:"
          ls -la data/
          
      # 4. 清理临时目录
      - name: Clean up temporary directory
        run: rm -rf temp-private-repo
        
      # 5. 提交更改（可选）
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/weather_data.json
          if ! git diff --staged --quiet; then
            git commit -m "自动更新天气数据 [skip ci]"
            git push
          else
            echo "没有更改，跳过提交"
          fi
