name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '30 */6 * * *'
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写入权限来推送更改
    
    steps:
    # 1. 拉取公共仓库（主分支）
    - name: Checkout public repo
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.ACCESS_TOKEN }}  # 使用具有写入权限的令牌

    # 2. 拉取私有仓库（天气数据）
    - name: Checkout private repo
      uses: actions/checkout@v4
      with:
        repository: su-12321/weather-
        token: ${{ secrets.ACCESS_TOKEN }}
        path: private-data

    # 3. 从私有仓库复制数据到公共仓库的 data 文件夹
    - name: Copy weather data
      run: |
        mkdir -p data
        cp private-data/weather_data.json data/
        cp private-data/joke.txt data/
        ls -la data/  # 调试：确认文件已复制

    # 4. 检查根目录静态资源
    - name: Check static assets
      run: |
        [ -f "luo_xiang.jpg" ] && echo "luo_xiang.jpg exists"
        [ -f "oc.png" ] && echo "oc.png exists"
        [ -f "omg.png" ] && echo "omg.png exists"

    # 5. 提交更改到主分支
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git status  # 查看更改状态
        git diff --cached --stat  # 查看将要提交的更改
        git commit -m "Update weather data - $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
        git push origin main
